name: Publish python package
description: |-
  A github action to publish a python package to test.pypi.org and pypi.org.
  Input options:
  - `test-only`: Publish only to test.pypi.org if set to `true` (default).
  Invoke with `uses: glenn20/python-ci/publish@v2`
author: glenn20

inputs:
  test-only:
    description: 'Publish only to test.pypi if `true` (default).'
    default: 'true'
    required: false

outputs:
  package-name:
    description: 'Name of the package'
    value: ${{ steps.package-name.outputs.name }}
  package-version:
    description: 'Version number of the package'
    value: ${{ steps.package-name.outputs.version }}
  url:
    description: 'URL of the package on pypi.org (or test.pypi.org)'
    value: https://${{ (inputs.test-only == 'true') && 'test.' || '' }}pypi.org/p/${{ steps.package-name.outputs.name }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Get package name and version
      id: package-name
      shell: bash
      run: >-
        ls dist/*.whl
        | sed 's/^.*\/\([^-]*\)-\([^-]*\)-.*$/name=\1\nversion=\2/;1q'
        | sed '/^name=/s/_/-/g'
        >> $GITHUB_OUTPUT

    - name: Publish to test.pypi
      shell: bash
      run: uv publish
      env:
        UV_PUBLISH_URL: https://test.pypi.org/legacy/
        # UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}

    - name: Publish to pypi.org
      if: ${{ inputs.test-only != 'true' }}
      shell: bash
      run: uv publish
      env:
        UV_PUBLISH_URL: https://pypi.org/legacy/
        # UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
