name: Publish python package
description: |-
  A github action to publish a python package to pypi.org or test.pypi.org.
  Input options:
  - `pypi: test.pypi` or `pypi: pypi`: Publish to test.pypi or pypi.org.
  Invoke with `uses: glenn20/python-ci/publish@v1`
author: glenn20
inputs:
  pypi:
    description: 'Set to "pypi" or "test.pypi" (default).'
    default: 'test.pypi'
    required: false
    type: string
# secrets:
#   pypi_token:
#     description: 'PyPI API token'
#     default: ''
#     required: false
#     type: string
outputs:
  package-name:
    description: 'Name of the package'
    value: ${{ steps.package-name.outputs.name }}
  package-version:
    description: 'Version number of the package'
    value: ${{ steps.package-name.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Get package name and version
      id: package-name
      run: >-
        ls dist/*.whl
        | sed 's/^.*\/\([^-]*\)-\([^-]*\)-.*$/name=\1\nversion=\2/;1q'
        | sed '/^name=/s/_/-/g'
        >> $GITHUB_OUTPUT
      shell: bash

    - name: Publish python package
      run: uv publish -vvvv
      env:
        UV_PUBLISH_URL: https://${{ inputs.pypi }}.org/legacy/
        # UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
      shell: bash

    # - name: Publish python package
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     repository-url: https://${{ inputs.pypi }}.org/legacy/
    #     # password: ${{ secrets.pypi_token }}
    #     verbose: true

