name: Publish python package
description: |-
  A github action to publish a python package to pypi.org or test.pypi.org.
  Input options:
  - `use-uv: true`: Use `uv publish` to publish the package.
  - `use-uv: false`: Use `pypa/gh-action-pypi-publish` to publish the package.
  - `pypi: test.pypi` or `pypi: pypi`: Publish to test.pypi or pypi.org.
  Invoke with `uses: glenn20/python-ci/publish@v1`
author: glenn20
inputs:
  pypi:
    description: 'Set to "pypi" or "test.pypi" (default).'
    default: 'test.pypi'
    required: false
    type: string
  use-uv:
    description: 'Use `uv` or `pypa` to publish the package.'
    default: false
    required: false
    type: boolean
# secrets:
#   pypi_token:
#     description: 'PyPI API token'
#     default: ''
#     required: false
#     type: string

runs:
  using: 'composite'
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Publish python package
      if: ${{ inputs.use-uv }}
      run: uv publish -vvvv
      env:
        UV_PUBLISH_URL: https://${{ inputs.pypi }}.org/legacy/
        # UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
      shell: bash

    - name: Publish distribution 📦 to PyPI
      if: ${{ !inputs.use-uv }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://${{ inputs.pypi }}.org/legacy/
        # password: ${{ secrets.pypi_token }}
        verbose: true

