name: Publish python package
description: Publish python package
author: glenn20
inputs:
  package-name:
    description: 'Name of the package to publish'
    required: true
    type: string
  pypi:
    description: 'Set to "pypi" or "test.pypi" (default).'
    default: 'test.pypi'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    # - name: Publish python package
    #   run: uv publish -vvvv
    #   env:
    #     UV_PUBLISH_URL: https://${{ inputs.pypi }}.org/legacy/
    #   shell: bash

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

