name: Setup python environment
description: Setup python environment
author: glenn20
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"
    type: string

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Install python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install python and setup project venv
      # Will install python version specified in pyproject.toml
      # Use --frozen so we don't update the uv.lock file
      # Use --no-sources to ignore source packages used in local development
      # Use --all-extras --dev to ensure we have everything needed for dev
      run: uv sync --frozen --no-sources --all-extras --dev
      shell: bash
