name: Setup python environment
description: |-
  A github action to setup the python environment for a project
  Uses `uv` to install python and setup the project venv
  Invoke with `uses: glenn20/python-ci/setup@v1`
author: glenn20

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install python-${{ inputs.python-version }}
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Setup project venv
      # Will install python version specified in pyproject.toml
      # Use --no-sources to ignore source packages used in local development
      # Use --all-extras --dev to ensure we have everything needed for dev
      run: uv sync --no-sources --all-extras --dev
      shell: bash
