name: Setup python environment
description: |-
  A github action to setup the python environment for a project
  Uses `uv` to install python and setup the project venv
  Invoke with `uses: glenn20/python-ci/setup@v1`
author: glenn20
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"
    type: string

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install python and setup project venv
      # Will install python version specified in pyproject.toml
      # Use --frozen so we don't update the uv.lock file
      # Use --no-sources to ignore source packages used in local development
      # Use --all-extras --dev to ensure we have everything needed for dev
      run: uv sync --frozen --no-sources --all-extras --dev
      shell: bash
