name: Create github release
# description: |-
#   A reusable github workflow to sign the python package files and upload to
#   a GitHub Release. Assumes the python package has been built and uploaded
#   prior.

on:
  workflow_call:
    inputs:
      tag:
        description: >-
          Version number of the package. Defaults to the current git tag
          if the workflow is triggered by a tag.
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  github-release:
    name: Sign the distribution and upload to GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Get package name and version
        id: package-name
        run: >-
          ls dist/*.whl |
          sed 's/^.*\/\([^-]*\)-\([^-]*\)-.*$/name=\1\nversion=\2/;1q'
          >> $GITHUB_OUTPUT

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          'v${{ steps.package-name.outputs.version }}'
          --repo '${{ github.repository }}'
          --notes ""

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          'v${{ steps.package-name.outputs.version }}'
          dist/**
          --repo '${{ github.repository }}'
