name: Tests

#   A reusable github workflow to run:
#   - code checks:
#     - `mypy` for type checks,
#     - `ruff check` for linting, and
#     - `ruff format` for code formatting.
#   - CI test suit:
#     - `pytest` for selected OS and python versions
#   - Build the python package and upload to github as a workflow artifact:
#     - `uv build`
#
#   Accepts the following inputs:
#   - `os`: A json string containing the list of operating systems on which to
#     run tests. Default is `["ubuntu-latest", "windows-latest",
#     "macos-latest"]`.
#   - `python-version`: A json string containing the list of python versions on
#     which to run tests. Default is `["3.9", "3.10", "3.11", "3.12", "3.13"]`.
#
#   Assumes the configurations for all tools (`mypy`, `uv`, `ruff`, `pytest`,
#   ...) are fully specified in config files (eg `pyproject.toml`).
#
#   Uses `uv run` to run the checks and tests.

on:
  workflow_call:
    inputs:
      os:
        description: >-
          A json string containing the list of operating systems on which to
          run the test matrix.
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
        type: string
        required: false
      python-version:
        description: >-
          A json string containing the list of python versions on
          which to run the test matrix.
        default: '["3.9", "3.10", "3.11", "3.12", "3.13"]'
        type: string
        required: false

jobs:
  checks:
    name: Code checks
    uses: glenn20/python-ci/.github/workflows/check.yaml@v1

  tests:
    name: Tests
    uses: glenn20/python-ci/.github/workflows/test.yaml@v1
    with:
      os: ${{ inputs.os }}
      python-version: ${{ inputs.python-version }}

  build:
    name: Build
    uses: glenn20/python-ci/.github/workflows/build.yaml@v1
