name: Code checks
# description: |-
#   A reusable github workflow to run code checks on the codebase, including
#   - `mypy` for type checks,
#   - `ruff check` for linting, and
#   - `ruff format` for code formatting.
#   Uses `uv run` to run the checks.

on:
  workflow_call:

jobs:
  checks:
    name: code checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout and setup python environment
        uses: glenn20/python-ci/setup@main

      - name: mypy
        run: uv run --no-sources mypy

      - name: lint
        run: uv run --no-sources ruff check

      - name: format
        run: uv run --no-sources ruff format --check
