name: Code checks
# description: |-
#   A reusable github workflow to run code checks on the codebase, including
#   - `mypy` for type checks,
#   - `ruff check` for linting, and
#   - `ruff format` for code formatting.
#   Uses `uv run` to run the checks.

on:
  workflow_call:

jobs:
  checks:
    name: code checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout and setup python environment
        uses: glenn20/python-ci/actions/setup@dev

      - name: mypy
        run: uv run --frozen mypy

      - name: lint
        run: uv run --frozen ruff check

      - name: format
        run: uv run --frozen ruff format --check
